export const SET_ALERT = "SET_ALERT";
export const SET_ALERT_SUB = "SET_ALERT_SUB";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REMOVE_ALERT_SUB = "REMOVE_ALERT_SUB";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UNKNOW_USER = "UNKNOW_USER";
export const WECHAT_NEW = "WECHAT_NEW";

// Am
export const AM_BASIC_NEW = "AM_BASIC_NEW";
export const AM_LOAD_ALL_LEADS = "AM_LOAD_ALL_LEADS";
export const AM_LOAD_ALL_COLLEGES = "AM_LOAD_ALL_COLLEGES";
export const AM_UPLOAD_SINGLE_LEAD = "AM_UPLOAD_SINGLE_LEAD";
export const AM_UPDATE_SINGLE_LEAD = "AM_UPDATE_SINGLE_LEAD";
export const AM_DELETE_SINGLE_LEAD = "AM_DELETE_SINGLE_LEAD";
export const AM_LOAD_ALL_PROFILES = "AM_LOAD_ALL_PROFILES";
export const AM_UPLOAD_SINGLE_PROFILE = "AM_UPLOAD_SINGLE_PROFILE";
export const AM_UPDATE_SINGLE_PROFILE = "AM_UPDATE_SINGLE_PROFILE";
export const AM_DELETE_SINGLE_PROFILE = "AM_DELETE_SINGLE_PROFILE";
export const AM_SAVING_PROFILELEAD = "AM_SAVING_PROFILELEAD";
export const AM_SETTING = "AM_SETTING";
export const AM_SET_STATISTIC = "AM_SET_STATISTIC";
export const AM_LOADING_FINISH = "AM_LOADING_FINISH";

// Admin
export const ADMIN_LOAD_ALL_COLLEGES = "ADMIN_LOAD_ALL_COLLEGES";
export const ADMIN_LOAD_ALL_USERS = "ADMIN_LOAD_ALL_USERS";
export const ADMIN_LOAD_ALL_LEADS = "ADMIN_LOAD_ALL_LEADS";
export const ADMIN_LOAD_ANALYZE_USER_LEADS = "ADMIN_LOAD_ANALYZE_USER_LEADS";
export const ADMIN_COLLEGES_NEW = "ADMIN_COLLEGES_NEW";
export const ADMIN_COLLEGES_DELETE = "ADMIN_COLLEGES_DELETE";
export const ADMIN_USER_UPDATE = "ADMIN_USER_UPDATE";

// Profiles
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
